export const EUROPEAN_CAPITALS = [
  { code: 'AL', name: 'Tirana' },
  { code: 'AT', name: 'Vienna' },
  { code: 'BE', name: 'Brussels' },
  { code: 'BG', name: 'Sofia' },
  { code: 'BA', name: 'Sarajevo' },
  { code: 'CH', name: 'Bern' },
  { code: 'CY', name: 'Nicosia' },
  { code: 'CZ', name: 'Prague' },
  { code: 'DE', name: 'Berlin' },
  { code: 'DK', name: 'Copenhagen' },
  { code: 'EE', name: 'Tallinn' },
  { code: 'ES', name: 'Madrid' },
  { code: 'FI', name: 'Helsinki' },
  { code: 'FR', name: 'Paris' },
  { code: 'GB', name: 'London' },
  { code: 'GR', name: 'Athens' },
  { code: 'HR', name: 'Zagreb' },
  { code: 'HU', name: 'Budapest' },
  { code: 'IE', name: 'Dublin' },
  { code: 'IS', name: 'Reykjavik' },
  { code: 'IT', name: 'Rome' },
  { code: 'LT', name: 'Vilnius' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'LV', name: 'Riga' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MD', name: 'Chisinau' },
  { code: 'ME', name: 'Podgorica' },
  { code: 'MK', name: 'Skopje' },
  { code: 'MT', name: 'Valletta' },
  { code: 'NL', name: 'Amsterdam' },
  { code: 'NO', name: 'Oslo' },
  { code: 'PL', name: 'Warsaw' },
  { code: 'PT', name: 'Lisbon' },
  { code: 'RO', name: 'Bucharest' },
  { code: 'RS', name: 'Belgrade' },
  { code: 'SE', name: 'Stockholm' },
  { code: 'SI', name: 'Ljubljana' },
  { code: 'SK', name: 'Bratislava' },
  { code: 'SM', name: 'San Marino' },
  { code: 'TR', name: 'Ankara' },
  { code: 'UA', name: 'Kyiv' },
  { code: 'VA', name: 'Vatican City' }
];